substitutions:
  name: m5stack-atom-echo-bbd268
  friendly_name: M5Stack Atom Echo bbd268
packages:
  m5stack.atom-echo-wake-word-voice-assistant: github://esphome/wake-word-voice-assistants/m5stack-atom-echo/m5stack-atom-echo.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: #yourkey


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

i2c:
  sda: GPIO25
  scl: GPIO21
  
#########################-----TIME-----##########################

time:
  - platform: homeassistant
    timezone: Europe/Moscow
    id: current_time
    on_time_sync:
      - component.update: uptime_timestamp

sensor:
  - platform: uptime
    name: "$devicename Uptime Sec"
    id: uptime_sec
    internal: true

  - platform: template
    id: uptime_timestamp
    name: "Device Uptime"
    device_class: "timestamp"
    accuracy_decimals: 0
    update_interval: never
    lambda: |-
      static float timestamp = (
        id(current_time).utcnow().timestamp - id(uptime_sec).state
      );
      return timestamp;

  - platform: homeassistant
    name: "Yemek Sıcaklık"
    entity_id: sensor.0x00124b0024cc2881_temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    id: yemekTEMP
    internal: true

  - platform: homeassistant
    name: "Yemek Nem"
    entity_id: sensor.0x00124b0024cc2881_humidity
    unit_of_measurement: "%"
    accuracy_decimals: 0
    id: yemekHUM
    internal: true

text_sensor:

  - platform: homeassistant
    name: "Name of Day"
    entity_id: sensor.turkishdayname
    id: dayNAME
    internal: true
    
  - platform: homeassistant
    name: "Turkish Full Date"
    entity_id: sensor.fulldate
    id: fullDATE
    internal: true

  - platform: homeassistant
    name: forecast
    id: d1minidisplayuptimetemplate
    entity_id: sensor.d1minidisplay_uptime_template
    internal: true

  - platform: homeassistant
    name: "Door Lock"
    entity_id: lock.lock_pro_matter
    id: doorlock
    internal: true

  - platform: homeassistant
    name: forecast
    id: weather_icon
    entity_id: weather.home
    internal: true

  - platform: homeassistant
    name: forecast
    id: satallitestate
    entity_id: assist_satellite.m5stack_atom_echo_bbd268_assist_satellite
    internal: true

###################################################################################################

globals:
  - id: blink_counter
    type: int
    restore_value: false
    initial_value: '0'
  
  - id: BLINK_THRESHOLD
    type: int
    initial_value: '1' # you can adjust the blink speed from here


display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    lambda: |-

      // --- Voice Assistant State Control ---
      std::string state = id(satallitestate).state;

      if (state != "idle") {
        it.fill(COLOR_OFF); 

      if (state == "listening") {
            id(blink_counter) = (id(blink_counter) + 1) % (id(BLINK_THRESHOLD) * 2);

            const char* question_mark_symbol = "\U000F1739"; 
            const char* blank_symbol = "\U000F0EDE";
            const char* current_symbol;

            if (id(blink_counter) < id(BLINK_THRESHOLD)) {
                current_symbol = question_mark_symbol;
            } else {
                current_symbol = blank_symbol;
            }

            it.printf(64, 45, id(chatsymbols), TextAlign::BOTTOM_CENTER, current_symbol); 
            it.printf(64, 55, id(bold_15), TextAlign::CENTER, "LISTENING"); 
        }
        else if (state == "processing") {
            id(blink_counter) = (id(blink_counter) + 1) % (id(BLINK_THRESHOLD) * 2);

            const char* question_mark_symbol = "\U000F12CA";
            const char* blank_symbol = "\U000F0EDE";
            const char* current_symbol2;

            if (id(blink_counter) < id(BLINK_THRESHOLD)) {
                current_symbol2 = question_mark_symbol;
            } else {
                current_symbol2 = blank_symbol;
            }

          // "İŞLİYORUM..." İki Satır
            it.printf(64, 45, id(chatsymbols), TextAlign::BOTTOM_CENTER, current_symbol2); 
            it.printf(64, 55, id(bold_15), TextAlign::CENTER, "PROCESSING"); 
        }
        else if (state == "responding") {
          it.printf(64, 45, id(chatsymbols), TextAlign::BOTTOM_CENTER, "\U000F12C9");  
          it.printf(64, 55, id(bold_15), TextAlign::CENTER, "RESPONSE");
        }

        return;  // normal ekrana geçme
      }

      // --- NORMAL EKRAN (idle modu) ---
      it.strftime(64, 32, id(bold_30), TextAlign::BOTTOM_CENTER, "%H:%M", id(current_time).now());
      it.printf(64, 40, id(medium_12), TextAlign::BOTTOM_CENTER, "%s", id(fullDATE).state.c_str());
      it.printf(64, 52, id(medium_12), TextAlign::BOTTOM_CENTER, "%s", id(dayNAME).state.c_str());  

      it.printf(5, 67, id(icons_16), TextAlign::BOTTOM_CENTER, "\U000F0F55");  
      if (id(yemekTEMP).has_state()) {
        it.printf(15, 67, id(medium_12), TextAlign::BOTTOM_LEFT, "%.1f", id(yemekTEMP).state);
      }

      it.printf(120, 67, id(icons_16), TextAlign::BOTTOM_CENTER, "\U000F1A86");  
      if (id(yemekHUM).has_state()) {
        it.printf(110, 67, id(medium_12), TextAlign::BOTTOM_RIGHT , "%.1f", id(yemekHUM).state);
      }

      if (id(doorlock).state == "locked") {
        it.printf(10, 24, id(icons_20), TextAlign::BOTTOM_CENTER, "\U000F099D");
      }

      // --- Weather Icons ---
      if (id(weather_icon).state == "clear-night") it.printf(118, 24, id(weathersymbols), TextAlign::BOTTOM_CENTER, "\U000F0594");
      if (id(weather_icon).state == "cloudy") it.printf(118, 24, id(weathersymbols), TextAlign::BOTTOM_CENTER, "\U000F0590");
      if (id(weather_icon).state == "partlycloudy") it.printf(118, 24, id(weathersymbols), TextAlign::BOTTOM_CENTER, "\U000F0595");
      if (id(weather_icon).state == "fog") it.printf(118, 24, id(weathersymbols), TextAlign::BOTTOM_CENTER, "\U000F0591");
      if (id(weather_icon).state == "hail") it.printf(118, 24, id(weathersymbols), TextAlign::BOTTOM_CENTER, "\U000F0592");
      if (id(weather_icon).state == "lightning") it.printf(118, 24, id(weathersymbols), TextAlign::BOTTOM_CENTER, "\U000F0593");
      if (id(weather_icon).state == "lightning-rainy") it.printf(118, 24, id(weathersymbols), TextAlign::BOTTOM_CENTER, "\U000F067E");
      if (id(weather_icon).state == "pouring") it.printf(118, 24, id(weathersymbols), TextAlign::BOTTOM_CENTER, "\U000F0596");
      if (id(weather_icon).state == "rainy") it.printf(118, 24, id(weathersymbols), TextAlign::BOTTOM_CENTER, "\U000F0597");
      if (id(weather_icon).state == "snowy") it.printf(118, 24, id(weathersymbols), TextAlign::BOTTOM_CENTER, "\U000F0F36");
      if (id(weather_icon).state == "snowy-rainy") it.printf(118, 24, id(weathersymbols), TextAlign::BOTTOM_CENTER, "\U000F067F");
      if (id(weather_icon).state == "sunny") it.printf(118, 24, id(weathersymbols), TextAlign::BOTTOM_CENTER, "\U000F0599");
      if (id(weather_icon).state == "windy") it.printf(118, 24, id(weathersymbols), TextAlign::BOTTOM_CENTER, "\U000F059D");
      if (id(weather_icon).state == "windy-variant") it.printf(118, 24, id(weathersymbols), TextAlign::BOTTOM_CENTER, "\U000F059E");
      if (id(weather_icon).state == "exceptional") it.printf(118, 24, id(weathersymbols), TextAlign::BOTTOM_CENTER, "\U000F0F38");



####################################################################################################


font:
  - file: 'fonts/Google_Sans_Bold.ttf'
    id: bold_30
    size: 30
    glyphs: 
      ['&', '@', '!', ',', '.', '"', '%', '+', '-', '_', ':', '°', '0',
        '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'Ç', 'D', 'E',
        'F', 'G', 'Ğ', 'H', 'I', 'İ', 'J', 'K', 'L', 'M', 'N', 'O', 'Ö', 'P', 'Q', 
        'R', 'S', 'Ş', 'T', 'U', 'Ü', 'V', 'W', 'X', 'Y', 'Z', ' ', 'a', 'b', 'c', 
        'ç', 'd', 'e', 'f', 'g', 'ğ', 'h', 'ı', 'i', 'j', 'k', 'l', 'm', 'n', 'o',
        'ö', 'p', 'q', 'r', 's', 'ş', 't', 'u', 'ü', 'v', 'w', 'x', 'y', 'z', '/',
        'è']    

  - file: 'fonts/Google_Sans_Bold.ttf'
    id: bold_24
    size: 24
    glyphs: 
      ['&', '@', '!', ',', '.', '"', '%', '+', '-', '_', ':', '°', '0',
        '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'Ç', 'D', 'E',
        'F', 'G', 'Ğ', 'H', 'I', 'İ', 'J', 'K', 'L', 'M', 'N', 'O', 'Ö', 'P', 'Q', 
        'R', 'S', 'Ş', 'T', 'U', 'Ü', 'V', 'W', 'X', 'Y', 'Z', ' ', 'a', 'b', 'c', 
        'ç', 'd', 'e', 'f', 'g', 'ğ', 'h', 'ı', 'i', 'j', 'k', 'l', 'm', 'n', 'o',
        'ö', 'p', 'q', 'r', 's', 'ş', 't', 'u', 'ü', 'v', 'w', 'x', 'y', 'z', '/',
        'è']   

  - file: 'fonts/Google_Sans_Bold.ttf'
    id: bold_20
    size: 20
    glyphs: 
      ['&', '@', '!', ',', '.', '"', '%', '+', '-', '_', ':', '°', '0',
        '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'Ç', 'D', 'E',
        'F', 'G', 'Ğ', 'H', 'I', 'İ', 'J', 'K', 'L', 'M', 'N', 'O', 'Ö', 'P', 'Q', 
        'R', 'S', 'Ş', 'T', 'U', 'Ü', 'V', 'W', 'X', 'Y', 'Z', ' ', 'a', 'b', 'c', 
        'ç', 'd', 'e', 'f', 'g', 'ğ', 'h', 'ı', 'i', 'j', 'k', 'l', 'm', 'n', 'o',
        'ö', 'p', 'q', 'r', 's', 'ş', 't', 'u', 'ü', 'v', 'w', 'x', 'y', 'z', '/',
        'è']   

  - file: 'fonts/Google_Sans_Bold.ttf'
    id: bold_15
    size: 15
    glyphs: 
      ['&', '@', '!', ',', '.', '"', '%', '+', '-', '_', ':', '°', '0',
        '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'Ç', 'D', 'E',
        'F', 'G', 'Ğ', 'H', 'I', 'İ', 'J', 'K', 'L', 'M', 'N', 'O', 'Ö', 'P', 'Q', 
        'R', 'S', 'Ş', 'T', 'U', 'Ü', 'V', 'W', 'X', 'Y', 'Z', ' ', 'a', 'b', 'c', 
        'ç', 'd', 'e', 'f', 'g', 'ğ', 'h', 'ı', 'i', 'j', 'k', 'l', 'm', 'n', 'o',
        'ö', 'p', 'q', 'r', 's', 'ş', 't', 'u', 'ü', 'v', 'w', 'x', 'y', 'z', '/',
        'è']  

  - file: 'fonts/Google_Sans_Medium.ttf'
    id: medium_12
    size: 12
    glyphs: 
      ['&', '@', '!', ',', '.', '"', '%', '+', '-', '_', ':', '°', '0',
        '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'Ç', 'D', 'E',
        'F', 'G', 'Ğ', 'H', 'I', 'İ', 'J', 'K', 'L', 'M', 'N', 'O', 'Ö', 'P', 'Q', 
        'R', 'S', 'Ş', 'T', 'U', 'Ü', 'V', 'W', 'X', 'Y', 'Z', ' ', 'a', 'b', 'c', 
        'ç', 'd', 'e', 'f', 'g', 'ğ', 'h', 'ı', 'i', 'j', 'k', 'l', 'm', 'n', 'o',
        'ö', 'p', 'q', 'r', 's', 'ş', 't', 'u', 'ü', 'v', 'w', 'x', 'y', 'z', '/',
        'è']    

  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: icons_16
    size: 16
    glyphs:
      - "\U000F0F55" # Temperature
      - "\U000F1A86" # Humidify  \U000F099D
      - "\U000F099D" # Lock

  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: icons_20
    size: 20
    glyphs:
      - "\U000F0F55" # Temperature
      - "\U000F1A86" # Humidify  \U000F099D
      - "\U000F099D" # Lock

  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: weathersymbols
    size: 22
    glyphs:
      - "\U000F0F55" # Temperature
      - "\U000F1A86" # Humidify  \U000F099D
      - "\U000F099D" # Lock
      - "\U000F0594" # clear-night
      - "\U000F0590" # cloudy
      - "\U000F0595" # partlycloudy
      - "\U000F0591" # fog      
      - "\U000F0592" # hail
      - "\U000F0593" # lightning
      - "\U000F067E" # lightning-rainy
      - "\U000F0596" # pouring
      - "\U000F0597" # rainy
      - "\U000F0F36" # snowy
      - "\U000F067F" # snowy-rainy
      - "\U000F0599" # sunny
      - "\U000F059D" # windy
      - "\U000F059E" # windy-variant
      - "\U000F0F38" # exceptional  
      - "\U000F0EDE" # chat empty
      - "\U000F1739" # chat question
      - "\U000F12CA" # chat dots
      - "\U000F12C9" # chat answer

  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: chatsymbols
    size: 45
    glyphs:
      - "\U000F0EDE" # chat empty
      - "\U000F1739" # chat question
      - "\U000F12CA" # chat dots
      - "\U000F12C9" # chat answer